# Generated by Django 4.0.5 on 2022-06-16 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_remove_korisnik_role_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='predmeti',
            name='nositelj_kolegija',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nositelj_kolegija', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('PROFESOR', 'profesor'), ('STUDENT', 'student')], max_length=50),
        ),
    ]



