# Generated by Django 4.0.5 on 2022-06-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_predmeti_nositelj_kolegija_alter_role_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnik',
            name='role',
            field=models.CharField(choices=[('prof', 'profesor'), ('stu', 'student')], default='stud', max_length=50),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
