# Generated by Django 4.0.5 on 2022-06-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0007_alter_predmeti_izborni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='role',
            field=models.CharField(choices=[('profesor', 'profesor'), ('stududent', 'student')], max_length=50),
        ),
    ]
