# Generated by Django 4.0.5 on 2022-06-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0008_alter_korisnik_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upisnilist',
            name='status',
            field=models.CharField(choices=[('pass', 'pass'), ('enrolled', 'enrolled')], max_length=50),
        ),
    ]
